server:
  port: 8084

spring:
  application:
    name: APIGATEWAY

  cloud:
    gateway:
      mvc:
        routes:
          - id: USERSERVICE
            uri: lb://USERSERVICE
            predicates:
              - Path=/user/**

          - id: RATINGSERVICE
            uri: lb://RATINGSERVICE
            predicates:
              - Path=/rating/**

          - id: HOTELSERVICE
            uri: lb://HOTELSERVICE
            predicates:
              - Path=/hotel/**
  config:
    import: configserver:http://localhost:8085

  profiles:
    active: dev
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka